general:
  folder_path: ""
  export_folder_path: "D:/jilu"
  user_name: "王丹丹"
  auto_startup: true
  minimize_to_tray: true
  dont_ask_again: false
  hide_previous_months: false
  simple_export_mode: false

timer:
  enabled: true
  require_24h: true
  times: "10:00,16:00"
  grace_minutes: 10